# Generated by Django 4.0.5 on 2022-06-05 07:16

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.CharField(blank=True, choices=[('CA', 'Within Canada'), ('Abroad', 'Outside Canada')], max_length=30, null=True)),
                ('p_type', models.CharField(choices=[('Library', 'Library'), ('Conservation Park', 'Conservation Park'), ('Gallery', 'Gallery')], max_length=30)),
                ('entry_fee', models.DecimalField(decimal_places=2, max_digits=60)),
                ('parking', models.CharField(blank=True, choices=[('free', 'free'), ('per hour', 'per hour'), ('per day', 'per day')], max_length=30, null=True)),
                ('buddy_num', models.IntegerField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
