# Generated by Django 4.0.5 on 2022-06-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.CharField(blank=True, choices=[('CA', 'Within the Canada'), ('Abroad', 'Outside the Canada')], max_length=30, null=True),
        ),
    ]
