# Generated by Django 4.0.5 on 2022-06-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='p_type',
            new_name='parking_type',
        ),
    ]
