# Generated by Django 4.0.5 on 2022-06-12 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_rename_p_type_place_parking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='parking_type',
            new_name='place_type',
        ),
    ]
