# Generated by Django 4.0.5 on 2022-06-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_rename_parking_type_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
