# Generated by Django 4.0.5 on 2022-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_place_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='pic1',
            field=models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='place',
            name='pic2',
            field=models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='place',
            name='pic3',
            field=models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic/%Y/%m/%d/'),
        ),
    ]
