# Generated by Django 4.0.5 on 2022-06-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_remove_place_location_place_creator_place_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='area',
            field=models.CharField(blank=True, choices=[('Within the Canada', 'Within the Canada'), ('Outside the Canada', 'Outside the Canada')], max_length=30, null=True),
        ),
    ]
